language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'

os:
  - linux

addons:
  apt:
    packages:
    - libudev-dev

cache: pip

install:
  - python -m pip install --upgrade pip setuptools wheel twine

script:
  - python setup.py sdist bdist_wheel

deploy:
  - python -m twine upload -u $PYPI_USER -p $PYPI_PASS --skip-existing dist/*

notifications:
  email: false
